services:
  - type: web
    name: hotel-ai-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "PYTHONPATH=src python src/hotel_ai/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      
