services:
  - type: web
    name: hotel-ai-webhook
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/hotel_ai/webhook_server.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: seu_bot_token
      - key: BASEROW_API_TOKEN
        value: seu_token
