classify_message_task:
  agent: message_classifier
  description: >
    Analise a mensagem recebida do cliente e classifique seu nível de resolução e o departamento ideal.
    Inclua também a mensagem original no resultado.
  expected_output: >
    Um JSON com as seguintes chaves:
    {
      "nivel": "baixo | médio | alto",
      "departamento": "Atendimento | Manutenção | Limpeza | Outro",
      "mensagem": "Texto original da mensagem"
    }

dispatch_task:
  agent: dispatcher
  description: >
    Registre a solicitação do cliente na base de dados Baserow usando os dados classificados anteriormente.
  expected_output: >
    Uma string confirmando que a solicitação foi registrada com sucesso, ou um erro detalhado.

respond_client_task:
  agent: response_agent
  description: >
    Gere uma resposta cordial ao cliente com base na solicitação registrada, informando que sua demanda foi encaminhada ao setor responsável.
  expected_output: >
    Uma resposta pronta para ser enviada ao cliente pelo Telegram.
