classify_message_task:
  agent: message_classifier
  description: >
    Você é responsável por classificar mensagens enviadas por hóspedes de um hotel.

    Analise cuidadosamente o conteúdo da mensagem recebida e:

    1. Identifique o **departamento ideal** para resolver a solicitação.
       Escolha **apenas um dos seguintes**:
       - Recepção
       - Concierge
       - Manutenção
       - Governança
       - Salão
       - Cozinha

    2. Classifique a **complexidade da solicitação** como:
       - Fácil (pode ser resolvida rapidamente e sem esforço técnico)
       - Médio (requer alguma coordenação ou verificação)
       - Difícil (envolve múltiplos setores, esforço técnico ou tempo prolongado)

    3. Retorne também a **mensagem original** enviada pelo cliente.

    Considere o **contexto e teor** da mensagem. Evite suposições ou respostas genéricas. Seja objetivo e preciso na análise.

    Mensagem:
    {mensagem_cliente}
  expected_output: >
    Um JSON com as seguintes chaves:
      - "mensagem": a mensagem original do cliente,
      - "nivel": o nível de complexidade (Fácil, Médio ou Difícil),
      - "departamento": o departamento mais adequado (entre: Recepção, Concierge, Manutenção, Governança, Salão, Cozinha)


dispatch_task:
  agent: dispatcher
  description: >
    Registre a solicitação do cliente na base de dados Baserow usando os dados classificados anteriormente.
    Retorne os mesmos dados recebidos com um campo adicional "status" contendo o resultado da tentativa de registro.
  expected_output: >
    Um JSON contendo as chaves:
      - "mensagem": a mensagem original do cliente,
      - "nivel": o nível de complexidade,
      - "departamento": o departamento identificado,
      - "status": uma string com o resultado do registro (ex: "✅ Solicitação registrada com sucesso no Baserow.")


respond_client_task:
  agent: response_agent
  description: >
    Gere uma resposta cordial ao cliente com base na solicitação registrada, informando que sua demanda foi encaminhada ao setor responsável.
  expected_output: >
    Uma resposta pronta para ser enviada ao cliente pelo Telegram.
