classify_message_task:
  description: >
    Analise a mensagem recebida do cliente e classifique seu nível de resolução e departamento ideal.
    Inclua também a própria mensagem original como campo "mensagem".
    
    Mensagem recebida:
    {mensagem_cliente}
  expected_output: >
    Um JSON com as chaves obrigatórias: "nivel", "departamento", "mensagem".
    Exemplo:
    {
      "nivel": "baixo",
      "departamento": "Atendimento",
      "mensagem": "{mensagem_cliente}"
    }

dispatch_task:
  description: >
    Registre a solicitação no Baserow usando os dados classificados. 
    Use os campos: mensagem, nivel, departamento.
  expected_output: >
    Confirmação de que a solicitação foi registrada corretamente.

respond_client_task:
  description: >
    Gere uma resposta cordial ao cliente explicando que a solicitação foi encaminhada ao setor correto.
  expected_output: >
    Uma mensagem de texto pronta para enviar ao cliente.
